# Site settings
title: Homepage
description:
baseurl: "/startpage" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
encoding: "utf-8"
markdown: kramdown
theme:
plugins_dir:
include:
exclude:

# Reading Files
include:
exclude:
  - LICENSE
  - README

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compact # :nested :expanded :compact :compressed
